sudo: required

services:
  - docker

language: python

python:
  - "2.7"

before-install:
  - pwd
  - wget -O docker https://get.docker.com/builds/Linux/x86_64/docker-latest
  
script:
  - id
  - sudo service docker stop
  - ./docker -d
