sudo: required

services:
  - docker

language: python

python:
  - "2.7"

script:
  - env
  - uname -a
  - cat /etc/issue
  - docker --version
  - git --version
  - zx --version
  - ps --version
  - cgcreate -h
