sudo: required

services:
  - docker

language: python

python:
  - "2.7"

before_install:
  - pwd
  - wget -O docker https://get.docker.com/builds/Linux/x86_64/docker-latest
  - chmod +x docker
  
script:
  - id
  - sudo service docker stop
  - ls -lh | grep -F docker
  - sudo ./docker -d -g var_lib_docker

