sudo: required

language: python

python:
  - "2.7"

before_install:
  - wget -O /home/travis/bin/docker https://get.docker.com/builds/Linux/x86_64/docker-latest
  - '[[ -d "$HOME/bin" ]] || mkdir "$HOME/bin"'
  - chmod +x "$HOME/bin/docker"
  
script:
  - sudo docker -d -g var_lib_docker &
  - docker --version
  - docker ps

after_success:
  - echo 'success'

after_failure:
  - echo 'failure'
  
after_script:
  - sudo kill `sudo cat /var/run/docker.pid`
